# Generated by Django 5.1.3 on 2024-11-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contacts_anexos_alter_contacts_ie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
