# Generated by Django 5.1.3 on 2024-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contacts_nascimento_alter_contacts_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='celular',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
