# Generated by Django 5.1.3 on 2024-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contacts_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='complemento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='status',
            field=models.CharField(blank=True, default='ativo', max_length=255),
        ),
    ]
