# Generated by Django 5.1.3 on 2024-12-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contacts_complemento_alter_contacts_status'),
        ('erp', '0010_alter_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='erp.company'),
        ),
    ]
