# Generated by Django 5.1.2 on 2024-11-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_bankaccount_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank',
            new_name='name',
        ),
    ]
