# Generated by Django 5.1.2 on 2024-11-17 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_bank_bankaccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('contato', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount')),
            ],
        ),
    ]
