# Generated by Django 5.1.2 on 2024-11-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='TransactionForm',
        ),
    ]
