# Generated by Django 5.1.2 on 2024-11-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_transactions_transactionform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionForm',
            new_name='Transactions',
        ),
    ]
