# Generated by Django 5.1.2 on 2024-11-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_transactionform_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
