# Generated by Django 5.1.2 on 2024-11-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_transactions_tipo_alter_transactions_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='conta',
            field=models.ForeignKey(default='conta', on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount'),
        ),
    ]
