# Generated by Django 5.1.2 on 2024-11-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transactions_company_alter_transactions_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='company',
        ),
    ]
