# Generated by Django 5.1.3 on 2024-11-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_transactions_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='contato',
            field=models.CharField(default='...', max_length=255),
        ),
    ]
