# Generated by Django 5.1.3 on 2024-12-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contacts_complemento_alter_contacts_status'),
        ('finance', '0016_rename_name_bankaccount_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='contato',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contacts'),
        ),
    ]
