# Generated by Django 5.1.3 on 2024-12-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contacts_options_alter_contacts_company'),
        ('finance', '0017_alter_transactions_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='contato',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='contacts.contacts'),
        ),
    ]
