# Generated by Django 5.2.2 on 2026-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_categories_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
