# Generated by Django 5.1.2 on 2024-10-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='celular',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
