# Generated by Django 5.1.2 on 2024-10-19 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_company_celular_alter_company_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
