# Generated by Django 5.1.2 on 2024-10-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_company_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
