# Generated by Django 5.1.2 on 2024-10-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_company_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='celular',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
