# Generated by Django 5.1.3 on 2024-11-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_company_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos'),
        ),
    ]
