# Generated by Django 5.1.3 on 2024-11-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_delete_contacts'),
        ('erp', '0010_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, max_length=255)),
                ('pessoa', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('contribuinte', models.CharField(blank=True, max_length=255)),
                ('ie', models.IntegerField()),
                ('im', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('celular', models.CharField(blank=True, max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.PositiveIntegerField(blank=True)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('nascimento', models.DateField()),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('anexos', models.FileField(upload_to='media/anexos')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.company')),
            ],
        ),
    ]
