# Generated by Django 5.1.3 on 2024-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to='media/anexos'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='ie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='im',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='nascimento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tipo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
