# Generated by Django 5.1.2 on 2024-11-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0009_alter_company_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('bank', models.CharField(max_length=255)),
                ('agencia', models.CharField(blank=True, max_length=255, null=True)),
                ('conta', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='erp.company')),
            ],
        ),
    ]
