# Generated by Django 5.1.2 on 2024-11-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
