# Generated by Django 5.1.2 on 2024-11-20 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transactions_create_by_alter_transactions_conta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
