# Generated by Django 5.1.2 on 2024-11-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_transactions_transfer_alter_transactions_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transfer',
            new_name='linked',
        ),
    ]
