# Generated by Django 5.1.2 on 2024-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_rename_transfer_transactions_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
