# Generated by Django 5.1.2 on 2024-11-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_transactions_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount'),
        ),
    ]
