# Generated by Django 5.1.3 on 2024-11-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_transactions_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='conta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='categoria',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
