# Generated by Django 5.2.2 on 2026-01-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_categories_alter_transactions_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='nome',
        ),
    ]
