# Generated by Django 5.2.2 on 2026-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_rename_name_categories_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
