# Generated by Django 5.1.2 on 2024-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_company_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
