# Generated by Django 5.1.2 on 2024-11-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_company_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
